spring.application.name=Zomato-Application

spring.datasource.url=jdbc:mysql://localhost:3306/zomato_db
spring.datasource.username=zomato_user
spring.datasource.password=Zomato@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
